language: ruby

rvm:
- 2.6
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1

deploy:
  provider: rubygems
  api_key:
    secure: RTnIpOnr03UtGtv9/ZbXdOTUNtZWh+8LDN4682u/+EJpWtmb7b6ZL8an94fIjnEFSfG62xid3d/ktqtbbUfD5SEDcM3Pc8FVUk3UjYiQPZkx4VRJC1jutEAta4urKqzDCuLdKkTuJN38vUm0wwokWkYVxuXzI+uGIh6fjNVEvPKMshbsxsdLeJEWr6f6/tM9w7ww6ty99nAbMiv4AEULjenLifpjbkeV9oX1PC/6n4LpXbjs9+GxZ6G/sBXuOWjsqefkgvXf1qC395/1Z2aUV/Wpsz+pqFV+h30ULEnSZSI2DgpQku8Cpd1oHDoe78d2oL/EG0WlfP4SVc64cZZaOGNvSHLQmagPvs2nnRT5mmuGjvPcbQfkwKPIW4YT9Ft4d4OEiQiWdjq10e11anDJQsZCR0NGJ0ZhjVf8+XfX8/4akLi8D05kMj9degw2B1QRDV6lIAMJz7M7q1HBdq9BP9FokzTFjRFjqVxmxdwqHi6rnCeTMYhpSSHUw+fd6Vw+z3EXtOcv/J81bg6DYHLC70hyjN5DA7gm1QADZYXOh6yqIePtPIXl6d/44KpuFuEnwuwq+ZD4J6lPJjptZkuqDL3YD5EsiuFDXYW+jWPgVNtPnktcAFdb6U1992/yB7QSyDV5EBMybj4FaxC9Shs6kxFfyIz7g8v1I+gCl5B6Mhw=
  gem: calgo
  on:
    tags: true
    repo: donaldong/calgo
    branch: main
  skip_cleanup: 'true'
